/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package marketplaceusc;

import javax.swing.JFrame;

public class Menu extends javax.swing.JPanel {

    /**
     * Creates new form Menu
     */
    private EventMenuSelected event;
    
    public void addEventMenuSelected(EventMenuSelected event){
        this.event = event;
        listMenu1.addEventMenuSelected(event);
    }
    public Menu() {
        initComponents();
        setOpaque(false);
        listMenu1.setOpaque(false);
        init();
    }

    private void init() {
        listMenu1.addItem(new Model_Menu("1","Home", Model_Menu.MenuType.MENU));
        listMenu1.addItem(new Model_Menu("2", "Profile", Model_Menu.MenuType.MENU));
        listMenu1.addItem(new Model_Menu(" ", " ", Model_Menu.MenuType.EMPTY));
        listMenu1.addItem(new Model_Menu(" ", " ", Model_Menu.MenuType.EMPTY));
       
        listMenu1.addItem(new Model_Menu("5", "Top Selling", Model_Menu.MenuType.MENU));
        listMenu1.addItem(new Model_Menu("6", "Top Sellers", Model_Menu.MenuType.MENU));
        listMenu1.addItem(new Model_Menu("7", "Uniforms", Model_Menu.MenuType.MENU));
        listMenu1.addItem(new Model_Menu("8", "School Books", Model_Menu.MenuType.MENU));
        listMenu1.addItem(new Model_Menu("9", "Lab Equipment", Model_Menu.MenuType.MENU));
        listMenu1.addItem(new Model_Menu("10", "Others", Model_Menu.MenuType.MENU));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toppanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dividerdashboard = new javax.swing.JPanel();
        middlepanel = new javax.swing.JPanel();
        listMenu1 = new marketplaceusc.ListMenu<>();
        categoriessdashboard = new javax.swing.JLabel();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(200, 724));

        toppanel.setBackground(new java.awt.Color(73, 95, 65));
        toppanel.setForeground(new java.awt.Color(255, 255, 255));
        toppanel.setPreferredSize(new java.awt.Dimension(300, 71));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("USC MARKETPLACE");

        javax.swing.GroupLayout toppanelLayout = new javax.swing.GroupLayout(toppanel);
        toppanel.setLayout(toppanelLayout);
        toppanelLayout.setHorizontalGroup(
            toppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toppanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        toppanelLayout.setVerticalGroup(
            toppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toppanelLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(24, 24, 24))
        );

        dividerdashboard.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout dividerdashboardLayout = new javax.swing.GroupLayout(dividerdashboard);
        dividerdashboard.setLayout(dividerdashboardLayout);
        dividerdashboardLayout.setHorizontalGroup(
            dividerdashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        dividerdashboardLayout.setVerticalGroup(
            dividerdashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        middlepanel.setBackground(new java.awt.Color(73, 95, 65));

        listMenu1.setBackground(new java.awt.Color(73, 95, 65));
        listMenu1.setMinimumSize(new java.awt.Dimension(100, 300));

        categoriessdashboard.setBackground(new java.awt.Color(73, 95, 65));
        categoriessdashboard.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        categoriessdashboard.setForeground(new java.awt.Color(255, 255, 255));
        categoriessdashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        categoriessdashboard.setText("Categories");
        categoriessdashboard.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout middlepanelLayout = new javax.swing.GroupLayout(middlepanel);
        middlepanel.setLayout(middlepanelLayout);
        middlepanelLayout.setHorizontalGroup(
            middlepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
            .addGroup(middlepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(listMenu1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
            .addGroup(middlepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(middlepanelLayout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(categoriessdashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(22, Short.MAX_VALUE)))
        );
        middlepanelLayout.setVerticalGroup(
            middlepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
            .addGroup(middlepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, middlepanelLayout.createSequentialGroup()
                    .addGap(0, 16, Short.MAX_VALUE)
                    .addComponent(listMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(middlepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(middlepanelLayout.createSequentialGroup()
                    .addGap(116, 116, 116)
                    .addComponent(categoriessdashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(403, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toppanel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(middlepanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(dividerdashboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toppanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(middlepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(71, 71, 71)
                    .addComponent(dividerdashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(648, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel categoriessdashboard;
    private javax.swing.JPanel dividerdashboard;
    private javax.swing.JLabel jLabel1;
    private marketplaceusc.ListMenu<String> listMenu1;
    private javax.swing.JPanel middlepanel;
    private javax.swing.JPanel toppanel;
    // End of variables declaration//GEN-END:variables
}
