/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package marketplaceusc;

import java.awt.BorderLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.awt.HeadlessException;
import java.security.SecureRandom;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Logger; 
import java.util.logging.Level; 



/**
 *
 * @author shewe
 */
public class Register extends javax.swing.JFrame {

    private int xOffset = 0;
    private int yOffset = 0;
    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        makeDraggable();
    }
    
     private void makeDraggable() {
        addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                xOffset = e.getX();
                yOffset = e.getY();
            }
        });

        addMouseMotionListener(new MouseAdapter() {
            @Override
            public void mouseDragged(MouseEvent e) {
                setLocation(getLocation().x + e.getX() - xOffset, getLocation().y + e.getY() - yOffset);
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        firstname = new javax.swing.JLabel();
        lastname = new javax.swing.JLabel();
        idnumber = new javax.swing.JLabel();
        sex = new javax.swing.JLabel();
        sex1 = new javax.swing.JLabel();
        firstnamefield = new javax.swing.JTextField();
        lastnamefield = new javax.swing.JTextField();
        idnumberfield = new javax.swing.JTextField();
        mobilenumberfield = new javax.swing.JTextField();
        sexfield1 = new javax.swing.JTextField();
        signupbutton = new javax.swing.JButton();
        closebutton = new javax.swing.JLabel();
        minimizebutton = new javax.swing.JLabel();
        idnumber1 = new javax.swing.JLabel();
        idnumber2 = new javax.swing.JLabel();
        idnumberfield1 = new javax.swing.JTextField();
        schoolemailfield = new javax.swing.JTextField();
        backtologin = new javax.swing.JLabel();
        passwordfield = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(73, 95, 65));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setText("Sign Up ");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setText("Please fill in correct details.");

        firstname.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        firstname.setText("First Name");

        lastname.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lastname.setText("Last Name");

        idnumber.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        idnumber.setText("School Email");

        sex.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        sex.setText("Mobile Number");

        sex1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        sex1.setText("Sex");

        firstnamefield.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        firstnamefield.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        lastnamefield.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lastnamefield.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        idnumberfield.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        idnumberfield.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        idnumberfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idnumberfieldActionPerformed(evt);
            }
        });

        mobilenumberfield.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        mobilenumberfield.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        sexfield1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        sexfield1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        signupbutton.setBackground(new java.awt.Color(73, 95, 65));
        signupbutton.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        signupbutton.setForeground(new java.awt.Color(255, 255, 255));
        signupbutton.setText("Sign Up");
        signupbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signupbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signupbuttonMouseClicked(evt);
            }
        });

        closebutton.setText("X");
        closebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closebuttonMouseClicked(evt);
            }
        });

        minimizebutton.setText("--");
        minimizebutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimizebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizebuttonMouseClicked(evt);
            }
        });

        idnumber1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        idnumber1.setText("Password");

        idnumber2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        idnumber2.setText("ID Number");

        idnumberfield1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        idnumberfield1.setForeground(new java.awt.Color(153, 153, 153));
        idnumberfield1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        schoolemailfield.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        schoolemailfield.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        schoolemailfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schoolemailfieldActionPerformed(evt);
            }
        });

        backtologin.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        backtologin.setForeground(new java.awt.Color(0, 112, 224));
        backtologin.setText("Already have an account?");
        backtologin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backtologin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backtologinMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backtologinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backtologinMouseExited(evt);
            }
        });

        passwordfield.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        passwordfield.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(minimizebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(idnumberfield, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstnamefield, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstname)
                            .addComponent(idnumberfield1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sex1)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(backtologin)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(signupbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lastname)
                                        .addComponent(lastnamefield, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(idnumber2))
                                    .addGap(46, 46, 46)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(idnumber1)
                                        .addComponent(sex)
                                        .addComponent(mobilenumberfield)
                                        .addComponent(idnumber)
                                        .addComponent(schoolemailfield)
                                        .addComponent(passwordfield, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)))))
                        .addContainerGap(100, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(sexfield1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(signupbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(closebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(minimizebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstname)
                            .addComponent(sex))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstnamefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mobilenumberfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastname)
                            .addComponent(idnumber))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastnamefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(schoolemailfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idnumber1)
                            .addComponent(idnumber2))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idnumberfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(idnumberfield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(passwordfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16)
                        .addComponent(sex1)
                        .addGap(6, 6, 6)
                        .addComponent(sexfield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(backtologin)))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closebuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebuttonMouseClicked
        dispose();
    }//GEN-LAST:event_closebuttonMouseClicked

    private void minimizebuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizebuttonMouseClicked
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizebuttonMouseClicked

    private void idnumberfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idnumberfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idnumberfieldActionPerformed

    private void schoolemailfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schoolemailfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_schoolemailfieldActionPerformed

    private void backtologinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backtologinMouseClicked
        new Login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backtologinMouseClicked

    private void backtologinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backtologinMouseEntered
        backtologin.setText("<html><a href=''>Already have an account?</a></html>");
    }//GEN-LAST:event_backtologinMouseEntered

    private void backtologinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backtologinMouseExited
        backtologin.setText("Already have an account?");
    }//GEN-LAST:event_backtologinMouseExited

    private void signupbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupbuttonMouseClicked
        String firstName = firstnamefield.getText();
        String lastName = lastnamefield.getText();
        String schoolIdNumber = idnumberfield.getText();
        String sex = sexfield1.getText();
        String mobileNumber = mobilenumberfield.getText();
        String schoolEmail = schoolemailfield.getText();
        String password = passwordfield.getText();

        try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/users", "root", "");
             Statement state = con.createStatement()) {

            // Check if user with the same school ID number or email already exists
            var checkQuery = "SELECT * FROM userdetails WHERE schoolidnumber = '" + schoolIdNumber + "' OR schoolemail = '" + schoolEmail + "'";
            try (ResultSet resultSet = state.executeQuery(checkQuery)) {
                if (resultSet.next()) {
                    JOptionPane.showMessageDialog(null, "User with the same school ID number or email already exists.");
                    return; // Don't proceed with registration
                }
            }

            // Generate a recovery pin
            String recoveryPin = generateRandomRecoveryPin();

            // Save the recovery pin in the database
            saveRecoveryPinToDatabase(con, recoveryPin, schoolEmail);


            // Adjust the table name to userdetails
            String query = "INSERT INTO userdetails (firstname, lastname, schoolidnumber, sex, mobilenumber, schoolemail, password, pinrecovery) VALUES ('"
                    + firstName + "', '" + lastName + "', '" + schoolIdNumber + "', '" + sex + "', '"
                    + mobileNumber + "', '" + schoolEmail + "', '" + password + "', '" + recoveryPin + "')";

            if (firstName.isEmpty() || lastName.isEmpty() || schoolIdNumber.isEmpty()
                    || sex.isEmpty() || mobileNumber.isEmpty() || schoolEmail.isEmpty() || password.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please fill in all required fields.");
                return; // Don't proceed with registration
            }

            int result = state.executeUpdate(query);

            if (result > 0) {
                JOptionPane.showMessageDialog(null, "Registration Successful\nRecovery Pin: " + recoveryPin+"\nRecovery Pin for Forgotten Pasword");
                new Login().setVisible(true);
                this.setVisible(false);
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_signupbuttonMouseClicked

    private String generateRandomRecoveryPin() {
        String characters = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
        SecureRandom random = new SecureRandom();
        StringBuilder sb = new StringBuilder(10);
        for (int i = 0; i < 10; i++) {
            int randomIndex = random.nextInt(characters.length());
            sb.append(characters.charAt(randomIndex));
        }
        return sb.toString();
    }
    
    private void saveRecoveryPinToDatabase(Connection con, String recoveryPin, String email) {
        try {
            String query = "UPDATE userdetails SET recoverypin = ? WHERE schoolemail = ?";
            try (PreparedStatement pstmt = con.prepareStatement(query)) {
                pstmt.setString(1, recoveryPin);
                pstmt.setString(2, email);
                pstmt.executeUpdate();
            }
        } catch (SQLException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backtologin;
    private javax.swing.JLabel closebutton;
    private javax.swing.JLabel firstname;
    private javax.swing.JTextField firstnamefield;
    private javax.swing.JLabel idnumber;
    private javax.swing.JLabel idnumber1;
    private javax.swing.JLabel idnumber2;
    private javax.swing.JTextField idnumberfield;
    private javax.swing.JTextField idnumberfield1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lastname;
    private javax.swing.JTextField lastnamefield;
    private javax.swing.JLabel minimizebutton;
    private javax.swing.JTextField mobilenumberfield;
    private javax.swing.JPasswordField passwordfield;
    private javax.swing.JTextField schoolemailfield;
    private javax.swing.JLabel sex;
    private javax.swing.JLabel sex1;
    private javax.swing.JTextField sexfield1;
    private javax.swing.JButton signupbutton;
    // End of variables declaration//GEN-END:variables
}
