/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package marketplaceusc.dashboardpages;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.time.LocalDate;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import marketplaceusc.Login;

/**
 *
 * @author Elen Luz Gayondato
 */
public class Addpost extends javax.swing.JFrame {

    private int xOffset = 0;
    private int yOffset = 0;
    private String schoolemail;
    
    byte[] photo = null;
    String filename = null;
    
    public Addpost(String schoolEmail) {
        initComponents();
        makeDraggable();
        this.schoolemail = schoolEmail;
    }
    
    private byte[] convertImageToByteArray(BufferedImage image) {
    ByteArrayOutputStream baos = new ByteArrayOutputStream();
    try {
        ImageIO.write(image, "jpg", baos);
    } catch (IOException e) {
        e.printStackTrace();
        // Handle the exception as needed (e.g., show an error message)
    }
    return baos.toByteArray();
}
    
    private void makeDraggable() {
        addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                xOffset = e.getX();
                yOffset = e.getY();
            }
        });

        addMouseMotionListener(new MouseAdapter() {
            @Override
            public void mouseDragged(MouseEvent e) {
                setLocation(getLocation().x + e.getX() - xOffset, getLocation().y + e.getY() - yOffset);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        addpost_text = new javax.swing.JLabel();
        paragraph_field = new javax.swing.JLabel();
        condition_field = new javax.swing.JTextField();
        title_text = new javax.swing.JLabel();
        shortdescription_text = new javax.swing.JLabel();
        price_text = new javax.swing.JLabel();
        category_text = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        socialmedialink_text = new javax.swing.JLabel();
        image_text = new javax.swing.JLabel();
        socialmedialink_field = new javax.swing.JTextField();
        titlepost_field = new javax.swing.JTextField();
        price_field = new javax.swing.JTextField();
        category_field = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        shortdescriptionfield = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        uploadimage = new javax.swing.JButton();
        post_button = new javax.swing.JButton();
        filelink = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(73, 95, 65));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        addpost_text.setBackground(new java.awt.Color(255, 255, 255));
        addpost_text.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        addpost_text.setText("Add Post");

        paragraph_field.setBackground(new java.awt.Color(255, 255, 255));
        paragraph_field.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        paragraph_field.setText("Please fill in all fields.");

        title_text.setBackground(new java.awt.Color(255, 255, 255));
        title_text.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        title_text.setText("Title");

        shortdescription_text.setBackground(new java.awt.Color(255, 255, 255));
        shortdescription_text.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        shortdescription_text.setText("Short Description");

        price_text.setBackground(new java.awt.Color(255, 255, 255));
        price_text.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        price_text.setText("Price");

        category_text.setBackground(new java.awt.Color(255, 255, 255));
        category_text.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        category_text.setText("Category");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel7.setText("Condition");

        socialmedialink_text.setBackground(new java.awt.Color(255, 255, 255));
        socialmedialink_text.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        socialmedialink_text.setText("Social Media Link");

        image_text.setBackground(new java.awt.Color(255, 255, 255));
        image_text.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        image_text.setText("Image/s of Product");
        image_text.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        price_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                price_fieldActionPerformed(evt);
            }
        });

        category_field.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Uniforms", "School Books", "Lab Equipments/Wear", "Others" }));

        shortdescriptionfield.setColumns(20);
        shortdescriptionfield.setRows(5);
        jScrollPane1.setViewportView(shortdescriptionfield);

        jLabel10.setText("X");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        jLabel11.setText("--");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        uploadimage.setText("Upload Image");
        uploadimage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        uploadimage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadimageActionPerformed(evt);
            }
        });

        post_button.setBackground(new java.awt.Color(73, 95, 65));
        post_button.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        post_button.setForeground(new java.awt.Color(255, 255, 255));
        post_button.setText("Post");
        post_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        post_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                post_buttonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(titlepost_field, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(title_text, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(shortdescription_text, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(208, 208, 208)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(category_field, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(category_text, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(socialmedialink_text, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(addpost_text)
                                            .addComponent(paragraph_field)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jScrollPane1)
                                                    .addComponent(condition_field))
                                                .addGap(86, 86, 86)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(price_text, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(price_field, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                                                    .addComponent(socialmedialink_field)
                                                    .addComponent(image_text, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(uploadimage)
                                                    .addComponent(filelink, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(13, 13, 13)))
                                .addGap(0, 104, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addGap(15, 15, 15))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(post_button, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addpost_text)
                .addGap(0, 0, 0)
                .addComponent(paragraph_field)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title_text)
                    .addComponent(category_text))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titlepost_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(category_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shortdescription_text)
                    .addComponent(socialmedialink_text))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(socialmedialink_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(price_text)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(price_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(image_text))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(condition_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uploadimage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filelink, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(post_button)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void price_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_price_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_price_fieldActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void uploadimageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadimageActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        filename = f.getAbsolutePath();
        filelink.setText("Uploaded Succesfully");
    }//GEN-LAST:event_uploadimageActionPerformed

    private void post_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_post_buttonMouseClicked
        String title = titlepost_field.getText();
        String description = shortdescriptionfield.getText();
        String price = price_field.getText();
        String category = (String) category_field.getSelectedItem();
        String itemCondition = condition_field.getText();
        String refLink = socialmedialink_field.getText();
        
            byte[] imageBytes = null;
    try {
        BufferedImage bufferedImage = ImageIO.read(new File(filename));
        imageBytes = convertImageToByteArray(bufferedImage);
    } catch (IOException e) {
        e.printStackTrace();
        // Handle the exception as needed (e.g., show an error message)
        return; // Don't proceed with post if there's an error with the image
    }
    
    LocalDate currentDate = LocalDate.now();
    Date date = java.sql.Date.valueOf(currentDate);
    String schoolemailValue = schoolemail;
    

        try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/users", "root", "");
     PreparedStatement pstmt = con.prepareStatement("INSERT INTO activeposts (title, description, price, category, itemcondition, reflink, picture, infodate, schoolemail) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)")) {

    pstmt.setString(1, title);
    pstmt.setString(2, description);
    pstmt.setString(3, price);
    pstmt.setString(4, category);
    pstmt.setString(5, itemCondition);
    pstmt.setString(6, refLink);
    pstmt.setBytes(7, imageBytes); // Use setBytes for binary data
    pstmt.setDate(8, new java.sql.Date(date.getTime()));
    pstmt.setString(9, schoolemailValue);

            if (title.isEmpty() || description.isEmpty() || price.isEmpty()
                    || category.isEmpty() || itemCondition.isEmpty() || refLink.isEmpty() || date == null || schoolemailValue.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please fill in all required fields.");
                return; // Don't proceed with registration
            }
            if(imageBytes == null){
                JOptionPane.showMessageDialog(null, "Please fill in all required fields.");
                
            }

                    int result = pstmt.executeUpdate();
        
            if (result > 0) {
        JOptionPane.showMessageDialog(null, "Post Successful");
        // Additional code here if needed
    } else {
           JOptionPane.showMessageDialog(null, "Post Unsuccessful");
            }
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
        }
        this.setVisible(false);
    }//GEN-LAST:event_post_buttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Addpost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Addpost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Addpost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Addpost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Addpost(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addpost_text;
    private javax.swing.JComboBox<String> category_field;
    private javax.swing.JLabel category_text;
    private javax.swing.JTextField condition_field;
    private javax.swing.JLabel filelink;
    private javax.swing.JLabel image_text;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel paragraph_field;
    private javax.swing.JButton post_button;
    private javax.swing.JTextField price_field;
    private javax.swing.JLabel price_text;
    private javax.swing.JLabel shortdescription_text;
    private javax.swing.JTextArea shortdescriptionfield;
    private javax.swing.JTextField socialmedialink_field;
    private javax.swing.JLabel socialmedialink_text;
    private javax.swing.JLabel title_text;
    private javax.swing.JTextField titlepost_field;
    private javax.swing.JButton uploadimage;
    // End of variables declaration//GEN-END:variables
}
