/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package marketplaceusc.dashboardpages;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import javax.swing.JFrame;
import java.sql.*;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

public class Editpost extends javax.swing.JFrame {
    private int xOffset = 0;
    private int yOffset = 0;
    
    private Connection con;
    
     private String Oldtitle;
    private String Oldcategory;
    private ImageIcon image;
    private String schoolemail;
    
     private byte[] convertImageIconToBytes(ImageIcon icon) {
        BufferedImage bufferedImage = new BufferedImage(
                icon.getIconWidth(),
                icon.getIconHeight(),
                BufferedImage.TYPE_INT_ARGB
        );

        icon.paintIcon(null, bufferedImage.getGraphics(), 0, 0);

        ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();

        try {
            ImageIO.write(bufferedImage, "png", byteArrayOutputStream);
        } catch (IOException e) {
            e.printStackTrace();
        }

        return byteArrayOutputStream.toByteArray();
    }
    
    public Editpost(String title, String category, ImageIcon image, String schoolemail) {
        this.schoolemail = schoolemail;
        
        this.Oldtitle = title;
        this.Oldcategory = category;
        this.image = image;
        initComponents();
        makeDraggable();
        initializeDatabaseConnection();
        fetchData(Oldtitle, Oldcategory); // Fetch data when the frame is initialized
    }
    
        private void fetchData(String Title, String Category) {
        // Get the title and category from your existing data
       
        try {
            // Fetch query using title and category as identifiers
            String fetchQuery = "SELECT * FROM activeposts WHERE title=? AND category=?";

            try (PreparedStatement preparedStatement = con.prepareStatement(fetchQuery)) {
                // Set the parameters for the query
                preparedStatement.setString(1, Title);
                preparedStatement.setString(2, Category);

                // Execute the query
                ResultSet resultSet = preparedStatement.executeQuery();

                // Check if data is available
                if (resultSet.next()) {
                    // Populate the text fields with the fetched data
                    titlepost_field.setText(resultSet.getString("title"));
                    jTextArea1.setText(resultSet.getString("description"));
                    condition_field.setText(resultSet.getString("itemcondition"));
                    category_field.setSelectedItem(resultSet.getString("category"));
                    socialmedialink_field.setText(resultSet.getString("reflink"));
                    price_field.setText(resultSet.getString("price"));
                } else {
                    // No data found, handle accordingly
                    System.out.println("No data found for the specified title and category.");
                }
            } catch (SQLException ex) {
                // Handle any SQL errors
                ex.printStackTrace();
            }

        } catch (NumberFormatException e) {
            // Handle the case where price is not a valid double
            e.printStackTrace();
        }
    }

    
    private void makeDraggable() {
        addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                xOffset = e.getX();
                yOffset = e.getY();
            }
        });

        addMouseMotionListener(new MouseAdapter() {
            @Override
            public void mouseDragged(MouseEvent e) {
                setLocation(getLocation().x + e.getX() - xOffset, getLocation().y + e.getY() - yOffset);
            }
        });
    }
    
        private void initializeDatabaseConnection() {
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/users", "root", "");
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Addpostbackground2 = new javax.swing.JPanel();
        Addpost2 = new javax.swing.JLabel();
        Post2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        paragraph_field = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        title_text = new javax.swing.JLabel();
        shortdescription_text = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        category_text = new javax.swing.JLabel();
        socialmedialink_text = new javax.swing.JLabel();
        price_text = new javax.swing.JLabel();
        titlepost_field = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        condition_field = new javax.swing.JTextField();
        category_field = new javax.swing.JComboBox<>();
        socialmedialink_field = new javax.swing.JTextField();
        price_field = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        Addpostbackground2.setBackground(new java.awt.Color(255, 255, 255));

        Addpost2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        Addpost2.setText("Edit Post");

        Post2.setBackground(new java.awt.Color(73, 95, 65));
        Post2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Post2.setForeground(new java.awt.Color(249, 247, 243));
        Post2.setText("Finish");
        Post2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Post2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Post2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Post2ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(73, 95, 65));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        paragraph_field.setBackground(new java.awt.Color(255, 255, 255));
        paragraph_field.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        paragraph_field.setText("Please edit necessary fields.");

        jLabel1.setText("X");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setText("--");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        title_text.setBackground(new java.awt.Color(255, 255, 255));
        title_text.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        title_text.setText("Title");

        shortdescription_text.setBackground(new java.awt.Color(255, 255, 255));
        shortdescription_text.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        shortdescription_text.setText("Short Description");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel7.setText("Condition");

        category_text.setBackground(new java.awt.Color(255, 255, 255));
        category_text.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        category_text.setText("Category");

        socialmedialink_text.setBackground(new java.awt.Color(255, 255, 255));
        socialmedialink_text.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        socialmedialink_text.setText("Social Media Link");

        price_text.setBackground(new java.awt.Color(255, 255, 255));
        price_text.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        price_text.setText("Price");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        category_field.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Uniforms", "School Books", "Lab Equipments/Wear", "Others" }));

        price_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                price_fieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Addpostbackground2Layout = new javax.swing.GroupLayout(Addpostbackground2);
        Addpostbackground2.setLayout(Addpostbackground2Layout);
        Addpostbackground2Layout.setHorizontalGroup(
            Addpostbackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Addpostbackground2Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(Addpostbackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Addpostbackground2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(17, 17, 17))
                    .addGroup(Addpostbackground2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(Addpostbackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Addpostbackground2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Post2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Addpostbackground2Layout.createSequentialGroup()
                                .addGroup(Addpostbackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(title_text, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(paragraph_field)
                                    .addComponent(Addpost2)
                                    .addComponent(shortdescription_text, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(Addpostbackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(titlepost_field)
                                        .addComponent(jScrollPane1)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(condition_field)))
                                .addGap(80, 80, 80)
                                .addGroup(Addpostbackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(category_field, javax.swing.GroupLayout.Alignment.LEADING, 0, 213, Short.MAX_VALUE)
                                    .addComponent(socialmedialink_text, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(category_text, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(price_text, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(socialmedialink_field, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(price_field))
                                .addContainerGap(78, Short.MAX_VALUE))))))
        );
        Addpostbackground2Layout.setVerticalGroup(
            Addpostbackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Addpostbackground2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(Addpostbackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(8, 8, 8)
                .addComponent(Addpost2)
                .addGap(0, 0, 0)
                .addComponent(paragraph_field)
                .addGap(37, 37, 37)
                .addGroup(Addpostbackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title_text)
                    .addComponent(category_text))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Addpostbackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titlepost_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(category_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Addpostbackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(socialmedialink_text)
                    .addComponent(shortdescription_text))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Addpostbackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Addpostbackground2Layout.createSequentialGroup()
                        .addComponent(socialmedialink_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(price_text)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(price_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(condition_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(Post2)
                .addGap(27, 27, 27))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Addpostbackground2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Addpostbackground2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Post2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Post2ActionPerformed
  // Get the values from the text fields and other components
    String title = titlepost_field.getText();
    String description = jTextArea1.getText();
    String condition = condition_field.getText();
    String category = (String) category_field.getSelectedItem();
    String socialMediaLink = socialmedialink_field.getText();
    String price = price_field.getText();
    byte[] imageBytes = convertImageIconToBytes(image);

    // Validate the values if necessary

    try {
        // Update query using title and category as identifiers
String updateQuery = "UPDATE activeposts SET title=?, description=?, price=?,category=?, itemcondition=?, reflink=? WHERE title=? AND category=?";

        try (PreparedStatement preparedStatement = con.prepareStatement(updateQuery)) {
            // Set the parameters for the query
                preparedStatement.setString(1, title);
                preparedStatement.setString(2, description);
                preparedStatement.setString(3, price);
                preparedStatement.setString(4, category);
                preparedStatement.setString(5, condition);
                preparedStatement.setString(6, socialMediaLink);
                preparedStatement.setString(7, Oldtitle);
                preparedStatement.setString(8, Oldcategory);
                


            // Execute the update
            int rowsAffected = preparedStatement.executeUpdate();

            // Check if the update was successful
            if (rowsAffected > 0) {
                // Update successful
                System.out.println("Post updated successfully.");
            } else {
                // No rows were affected, update failed
                System.out.println("Failed to update post. Record not found.");
            }
        } catch (SQLException ex) {
            // Handle any SQL errors
            ex.printStackTrace();
        }
        new ItemSelling(schoolemail).setVisible(true);
        this.setVisible(false);

    } catch (NumberFormatException e) {
        // Handle the case where price is not a valid double
        e.printStackTrace();
    }    }//GEN-LAST:event_Post2ActionPerformed

    private void price_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_price_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_price_fieldActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Editpost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Editpost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Editpost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Editpost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Editpost(null, null, null, null).setVisible(true);
            }
        });
    } 



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Addpost2;
    private javax.swing.JPanel Addpostbackground2;
    private javax.swing.JButton Post2;
    private javax.swing.JComboBox<String> category_field;
    private javax.swing.JLabel category_text;
    private javax.swing.JTextField condition_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel paragraph_field;
    private javax.swing.JTextField price_field;
    private javax.swing.JLabel price_text;
    private javax.swing.JLabel shortdescription_text;
    private javax.swing.JTextField socialmedialink_field;
    private javax.swing.JLabel socialmedialink_text;
    private javax.swing.JLabel title_text;
    private javax.swing.JTextField titlepost_field;
    // End of variables declaration//GEN-END:variables
}
