/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package marketplaceusc.dashboardpages;

import java.awt.Desktop;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.net.URL;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Elen Luz Gayondato
 */
public class ItemsSellingPopUp extends javax.swing.JFrame {
    private int xOffset = 0;
    private int yOffset = 0;
    
     ImageIcon edit_icon = new ImageIcon("src\\marketplace\\icons\\edit_icon.png");
    
    String title;
    String description ;
    String price;
    String category;
    String itemCondition;
    String refLink;
    ImageIcon imageIcon;
    Date date;
    String schoolEmail;
    String mobilenumber;
            
    public ItemsSellingPopUp(String title,String description, String price,String category,
            String itemCondition, String refLink, ImageIcon imageIcon, Date date, String schoolEmail, String mobilenumber) {
        Image image = imageIcon.getImage();
        Image adjimg = image.getScaledInstance(248, 231, java.awt.Image.SCALE_SMOOTH);
        imageIcon = new ImageIcon(adjimg);
        this.title = title;
        this.description = description;
        this.price = price;
        this.category = category;
        this.itemCondition = itemCondition;
        this.refLink = refLink;
        this.imageIcon = imageIcon;
        this.date = date;
        this.schoolEmail = schoolEmail;
        this.mobilenumber = mobilenumber;
        
        
        initComponents(); 
        makeDraggable();
    }
    
    private void makeDraggable() {
        addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                xOffset = e.getX();
                yOffset = e.getY();
            }
        });

        addMouseMotionListener(new MouseAdapter() {
            @Override
            public void mouseDragged(MouseEvent e) {
                setLocation(getLocation().x + e.getX() - xOffset, getLocation().y + e.getY() - yOffset);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        ItemTitle = new javax.swing.JTextField();
        Price = new javax.swing.JTextField();
        Category1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        GreenHorizontal = new javax.swing.JPanel();
        Date = new javax.swing.JTextField();
        Condition = new javax.swing.JLabel();
        Category2 = new javax.swing.JTextField();
        Condition1 = new javax.swing.JLabel(imageIcon);
        ContactDetails = new javax.swing.JLabel();
        MobileNumber = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        UserRefLink = new javax.swing.JTextField();
        LinkText = new javax.swing.JLabel();
        Sold = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        exitbutton1 = new javax.swing.JLabel();
        minimizebutton = new javax.swing.JLabel();
        EditIcon = new javax.swing.JLabel(edit_icon);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(757, 433));
        setMinimumSize(new java.awt.Dimension(757, 433));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(757, 433));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(73, 95, 65));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 433, Short.MAX_VALUE)
        );

        ItemTitle.setEditable(false);
        ItemTitle.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        ItemTitle.setText(title);
        ItemTitle.setBorder(null);
        ItemTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemTitleActionPerformed(evt);
            }
        });

        Price.setEditable(false);
        Price.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        Price.setText(price);
        Price.setBorder(null);
        Price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PriceActionPerformed(evt);
            }
        });

        Category1.setEditable(false);
        Category1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        Category1.setText(category);
        Category1.setBorder(null);
        Category1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Category1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setText("Description");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText(description
        );
        jScrollPane1.setViewportView(jTextArea1);

        GreenHorizontal.setBackground(new java.awt.Color(73, 95, 65));
        GreenHorizontal.setPreferredSize(new java.awt.Dimension(100, 5));

        javax.swing.GroupLayout GreenHorizontalLayout = new javax.swing.GroupLayout(GreenHorizontal);
        GreenHorizontal.setLayout(GreenHorizontalLayout);
        GreenHorizontalLayout.setHorizontalGroup(
            GreenHorizontalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        GreenHorizontalLayout.setVerticalGroup(
            GreenHorizontalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        Date.setEditable(false);
        Date.setFont(new java.awt.Font("Verdana", 0, 8)); // NOI18N
        Date.setText(date.toString());
        Date.setBorder(null);
        Date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateActionPerformed(evt);
            }
        });

        Condition.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Condition.setText("Condition");

        Category2.setEditable(false);
        Category2.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        Category2.setText(itemCondition);
        Category2.setBorder(null);
        Category2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Category2ActionPerformed(evt);
            }
        });

        Condition1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        ContactDetails.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        ContactDetails.setText("Contact Details");

        MobileNumber.setEditable(false);
        MobileNumber.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        MobileNumber.setText(mobilenumber);
        MobileNumber.setBorder(null);
        MobileNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MobileNumberActionPerformed(evt);
            }
        });

        Email.setEditable(false);
        Email.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        Email.setText(schoolEmail);
        Email.setBorder(null);
        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });

        UserRefLink.setEditable(false);
        UserRefLink.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        UserRefLink.setForeground(new java.awt.Color(0, 112, 224));
        UserRefLink.setText(refLink);
        UserRefLink.setBorder(null);
        UserRefLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UserRefLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserRefLinkMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UserRefLinkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UserRefLinkMouseExited(evt);
            }
        });
        UserRefLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserRefLinkActionPerformed(evt);
            }
        });

        LinkText.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        LinkText.setText("Link:");

        Sold.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        Sold.setText("Sold");

        Delete.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        Delete.setText("Delete");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setText("₱");

        exitbutton1.setText("X");
        exitbutton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitbutton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitbutton1MouseClicked(evt);
            }
        });

        minimizebutton.setText("--");
        minimizebutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimizebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizebuttonMouseClicked(evt);
            }
        });

        EditIcon.setText(" ");
        EditIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditIconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Delete)
                                .addGap(104, 104, 104)
                                .addComponent(Sold))
                            .addComponent(Condition1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Condition)
                                    .addComponent(ContactDetails)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Category2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(MobileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(LinkText)
                                                .addGap(3, 3, 3)
                                                .addComponent(UserRefLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ItemTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(Category1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(Price, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(GreenHorizontal, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(EditIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(minimizebutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exitbutton1)
                        .addGap(15, 15, 15))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitbutton1)
                    .addComponent(minimizebutton))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ItemTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(Price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addComponent(GreenHorizontal, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(EditIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)
                                .addComponent(Category1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Condition)
                        .addGap(5, 5, 5)
                        .addComponent(Category2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Condition1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ContactDetails)
                    .addComponent(Delete)
                    .addComponent(Sold))
                .addGap(1, 1, 1)
                .addComponent(MobileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserRefLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LinkText))
                .addGap(61, 61, 61))
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ItemTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemTitleActionPerformed

    private void PriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PriceActionPerformed

    private void Category1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Category1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Category1ActionPerformed

    private void DateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateActionPerformed

    private void Category2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Category2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Category2ActionPerformed

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailActionPerformed

    private void UserRefLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserRefLinkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserRefLinkActionPerformed
    
    private String toStringUserRefLink () {
        String RefLink = UserRefLink.getText();
        return RefLink;
    }
    
    private void UserRefLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserRefLinkMouseClicked
        String RefLink = toStringUserRefLink();
        String UserLink = "http://" + RefLink;
        try {
            Desktop.getDesktop().browse(new URL (UserLink).toURI());
        }
        catch (Exception e)
        {}
    }//GEN-LAST:event_UserRefLinkMouseClicked

    private void MobileNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MobileNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MobileNumberActionPerformed

    private void minimizebuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizebuttonMouseClicked
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizebuttonMouseClicked

    private void exitbutton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitbutton1MouseClicked
        dispose();
    }//GEN-LAST:event_exitbutton1MouseClicked

    private void UserRefLinkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserRefLinkMouseEntered
        String RefLink = toStringUserRefLink();
        UserRefLink.setText("<html><a href=' '>Sign Up</a></html>");
   
    }//GEN-LAST:event_UserRefLinkMouseEntered

    private void UserRefLinkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserRefLinkMouseExited
        String RefLink = toStringUserRefLink();
        UserRefLink.setText(RefLink);
    }//GEN-LAST:event_UserRefLinkMouseExited

    private void EditIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditIconMouseClicked
        new Editpost(title, category, imageIcon, schoolEmail).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_EditIconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ItemsSellingPopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ItemsSellingPopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ItemsSellingPopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ItemsSellingPopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ItemsSellingPopUp(null,null,null,null,null,null,null,null,null,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Category1;
    private javax.swing.JTextField Category2;
    private javax.swing.JLabel Condition;
    private javax.swing.JLabel Condition1;
    private javax.swing.JLabel ContactDetails;
    private javax.swing.JTextField Date;
    private javax.swing.JButton Delete;
    private javax.swing.JLabel EditIcon;
    private javax.swing.JTextField Email;
    private javax.swing.JPanel GreenHorizontal;
    private javax.swing.JTextField ItemTitle;
    private javax.swing.JLabel LinkText;
    private javax.swing.JTextField MobileNumber;
    private javax.swing.JTextField Price;
    private javax.swing.JButton Sold;
    private javax.swing.JTextField UserRefLink;
    private javax.swing.JLabel exitbutton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel minimizebutton;
    // End of variables declaration//GEN-END:variables
}
