/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package marketplaceusc.dashboardpages;

import java.awt.HeadlessException;
import java.beans.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import marketplaceusc.Login;

/**
 *
 * @author shewe
 */
public class Page_Profile extends javax.swing.JPanel {
    private String schoolemail;
    private String firstname, lastname;
      
    public Connection con;
    public java.sql.Statement state;
    
    public Page_Profile(String schoolemail) {
        this.schoolemail = schoolemail;
        
        try {
            //Class.forName("com.mysql.cj.jdbc.Driver");
             con = DriverManager.getConnection("jdbc:mysql://localhost:3306/users", "root", "");
             state = con.createStatement();
        } catch (HeadlessException | SQLException x) {
        } 
      
    boolean success = getFirstLastName();
    
    // Check if data retrieval was successful
    if (success) {
        // Proceed with initializing components and using the retrieved names
    } else {
        // Handle the case where data retrieval failed
        JOptionPane.showMessageDialog(this, "Error retrieving user details", "Error", JOptionPane.ERROR_MESSAGE);
    }        
        
        initComponents();
    }
    
    public boolean getFirstLastName(){
    try {
        String query = "SELECT firstname, lastname FROM userdetails WHERE schoolemail = ?";
        PreparedStatement preparedStatement = con.prepareStatement(query);
        preparedStatement.setString(1, schoolemail);
        
        ResultSet resultSet = preparedStatement.executeQuery();

        if (resultSet.next()) {
            firstname = resultSet.getString("firstname").toUpperCase();
            lastname = resultSet.getString("lastname").toUpperCase();
            return true; // Successfully retrieved data
        } else {
            return false; // No data found for the given schoolemail
        }
    } catch (SQLException ex) {
        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        return false; // Error occurred
    }
    }

    ImageIcon profileuser_icon = new ImageIcon("src\\marketplace\\icons\\profileuser.png");
    ImageIcon addpost_icon = new ImageIcon("src\\marketplace\\icons\\addicon.png");
    ImageIcon tosell_icon = new ImageIcon("src\\marketplace\\icons\\bagicon.png");

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PageprofileBG = new javax.swing.JPanel();
        Verticalgreenline = new javax.swing.JPanel();
        Horizontalgreenline = new javax.swing.JPanel();
        profileBG = new javax.swing.JPanel();
        AddPost = new javax.swing.JLabel(addpost_icon);
        ToSell = new javax.swing.JLabel(tosell_icon);
        nameunderline = new javax.swing.JPanel();
        NameField = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel(profileuser_icon);

        setBackground(new java.awt.Color(255, 255, 255));

        PageprofileBG.setBackground(new java.awt.Color(255, 255, 255));

        Verticalgreenline.setBackground(new java.awt.Color(73, 95, 65));

        javax.swing.GroupLayout VerticalgreenlineLayout = new javax.swing.GroupLayout(Verticalgreenline);
        Verticalgreenline.setLayout(VerticalgreenlineLayout);
        VerticalgreenlineLayout.setHorizontalGroup(
            VerticalgreenlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );
        VerticalgreenlineLayout.setVerticalGroup(
            VerticalgreenlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 421, Short.MAX_VALUE)
        );

        Horizontalgreenline.setBackground(new java.awt.Color(73, 95, 65));

        javax.swing.GroupLayout HorizontalgreenlineLayout = new javax.swing.GroupLayout(Horizontalgreenline);
        Horizontalgreenline.setLayout(HorizontalgreenlineLayout);
        HorizontalgreenlineLayout.setHorizontalGroup(
            HorizontalgreenlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        HorizontalgreenlineLayout.setVerticalGroup(
            HorizontalgreenlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        profileBG.setBackground(new java.awt.Color(249, 247, 243));
        profileBG.setMinimumSize(new java.awt.Dimension(0, 0));

        AddPost.setBackground(new java.awt.Color(249, 247, 243));
        AddPost.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        AddPost.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddPost.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddPostMouseClicked(evt);
            }
        });

        ToSell.setBackground(new java.awt.Color(249, 247, 243));
        ToSell.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        ToSell.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ToSell.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ToSellMouseClicked(evt);
            }
        });

        nameunderline.setBackground(new java.awt.Color(73, 95, 65));
        nameunderline.setPreferredSize(new java.awt.Dimension(320, 1));

        javax.swing.GroupLayout nameunderlineLayout = new javax.swing.GroupLayout(nameunderline);
        nameunderline.setLayout(nameunderlineLayout);
        nameunderlineLayout.setHorizontalGroup(
            nameunderlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );
        nameunderlineLayout.setVerticalGroup(
            nameunderlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        NameField.setEditable(false);
        NameField.setBackground(new java.awt.Color(249, 247, 243));
        NameField.setFont(new java.awt.Font("Verdana", 1, 28)); // NOI18N
        NameField.setText(firstname + " " + lastname);
        NameField.setBorder(null);
        NameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameFieldActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(249, 247, 243));
        jTextField1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jTextField1.setText(schoolemail);
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(249, 247, 243));
        jTextField2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jTextField2.setText("Add Post");
        jTextField2.setBorder(null);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(249, 247, 243));
        jTextField3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jTextField3.setText("Items Selling");
        jTextField3.setBorder(null);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(249, 247, 243));

        javax.swing.GroupLayout profileBGLayout = new javax.swing.GroupLayout(profileBG);
        profileBG.setLayout(profileBGLayout);
        profileBGLayout.setHorizontalGroup(
            profileBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileBGLayout.createSequentialGroup()
                .addGroup(profileBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profileBGLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(profileBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(profileBGLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(profileBGLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(profileBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(NameField)
                                    .addComponent(nameunderline, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(profileBGLayout.createSequentialGroup()
                        .addGroup(profileBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(profileBGLayout.createSequentialGroup()
                                .addGap(214, 214, 214)
                                .addComponent(AddPost, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profileBGLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)))
                        .addGap(117, 117, 117)
                        .addGroup(profileBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(profileBGLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ToSell, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        profileBGLayout.setVerticalGroup(
            profileBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileBGLayout.createSequentialGroup()
                .addGroup(profileBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profileBGLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameunderline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profileBGLayout.createSequentialGroup()
                        .addContainerGap(60, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)))
                .addGroup(profileBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AddPost, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ToSell, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(profileBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout PageprofileBGLayout = new javax.swing.GroupLayout(PageprofileBG);
        PageprofileBG.setLayout(PageprofileBGLayout);
        PageprofileBGLayout.setHorizontalGroup(
            PageprofileBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PageprofileBGLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(Verticalgreenline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(PageprofileBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PageprofileBGLayout.createSequentialGroup()
                        .addComponent(Horizontalgreenline, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(198, 198, 198))
                    .addGroup(PageprofileBGLayout.createSequentialGroup()
                        .addComponent(profileBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(129, 129, 129))))
        );
        PageprofileBGLayout.setVerticalGroup(
            PageprofileBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PageprofileBGLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(PageprofileBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Verticalgreenline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PageprofileBGLayout.createSequentialGroup()
                        .addComponent(profileBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(Horizontalgreenline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(100, 100, 100))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(PageprofileBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PageprofileBG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void NameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameFieldActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void AddPostMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddPostMouseClicked
        new Addpost(schoolemail).setVisible(true);
    }//GEN-LAST:event_AddPostMouseClicked

    private void ToSellMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ToSellMouseClicked
       new ItemSelling(schoolemail).setVisible(true);
       
    }//GEN-LAST:event_ToSellMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddPost;
    private javax.swing.JPanel Horizontalgreenline;
    private javax.swing.JTextField NameField;
    private javax.swing.JPanel PageprofileBG;
    private javax.swing.JLabel ToSell;
    private javax.swing.JPanel Verticalgreenline;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JPanel nameunderline;
    private javax.swing.JPanel profileBG;
    // End of variables declaration//GEN-END:variables
}
